services:
  - type: web
    name: livraison-express-angular
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/console
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 